# Generated by Django 4.1.2 on 2023-03-21 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fantapoma', '0023_remove_crew_athletes_remove_crew_club_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PALERMO SC', 'PALERMO SC'), ('TELIMAR', 'TELIMAR'), ('CUS PALERMO', 'CUS PALERMO'), ('PELOROROW', 'PELOROROW'), ('LAURIA CCR', 'LAURIA CCR'), ('AUGUSTA', 'AUGUSTA'), ('ORTIGIA', 'ORTIGIA'), ('UNIONE SICILIANA', 'UNIONE SICILIANA'), ('PARADISO', 'PARADISO')], max_length=50)),
                ('athletes', models.ManyToManyField(to='fantapoma.athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('time', models.TimeField(null=True)),
                ('boat_type', models.CharField(default='SINGOLO', max_length=20)),
                ('category', models.CharField(default='SENIOR', max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mix')], default='M', max_length=1)),
                ('type', models.CharField(choices=[('HEAT', 'Qualificazione'), ('FINAL', 'Finale')], default='FINAL', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('athletes', models.ManyToManyField(to='fantapoma.athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.club')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.race')),
            ],
        ),
    ]
