# Generated by Django 4.1.2 on 2023-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('REG', 'Regionale'), ('NAT', 'Nazionale')], default='REG', max_length=80),
        ),
    ]
