# Generated by Django 4.1.2 on 2023-04-02 05:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_athlete_alter_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(default=uuid.uuid4, max_length=200, unique=True),
        ),
    ]
