# Generated by Django 4.1.2 on 2023-04-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0023_remove_crew_athletes_remove_crew_club_and_more'),
        ('events', '0010_auto_20230402_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='athletes',
            field=models.ManyToManyField(blank=True, to='fantapoma.athlete'),
        ),
    ]
