# Generated by Django 4.1.2 on 2023-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_club_athletes_alter_crew_athletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(choices=[('PALERMO SC', 'PALERMO SC'), ('TELIMAR', 'TELIMAR'), ('CUS PALERMO', 'CUS PALERMO'), ('PELOROROW', 'PELOROROW'), ('LAURIA CCR', 'LAURIA CCR'), ('AUGUSTA', 'AUGUSTA'), ('ORTIGIA CC', 'ORTIGIA CC'), ('UNIONE SICILIANA', 'UNIONE SICILIANA'), ('PARADISO', 'PARADISO')], max_length=50),
        ),
    ]
