# Generated by Django 4.1.2 on 2024-01-26 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_club_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(choices=[('PALERMO SC', 'PALERMO SC'), ('TELIMAR', 'TELIMAR'), ('CUS PALERMO', 'CUS PALERMO'), ('PELOROROW', 'PELOROROW'), ('LAURIA CCR', 'LAURIA CCR'), ('AUGUSTA CN', 'AUGUSTA CN'), ('ORTIGIA CC', 'ORTIGIA CC'), ('UN SICILIANA', 'UNIONE SICILIANA'), ('PARADISO CN', 'PARADISO CN'), ('THALATTA SC', 'THALATTA SC'), ('MESSINA CN', 'MESSINA CN'), ('CUS CATANIA', 'CUS CATANIA'), ('MONDELLO', 'MONDELLO'), ('CARIDDI CC', 'CARIDDI CC')], max_length=50),
        ),
    ]
