# Generated by Django 4.1.2 on 2024-04-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_crew_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='enrolled',
            field=models.IntegerField(default=0),
        ),
    ]
