# Generated by Django 3.2.5 on 2022-05-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='first_time',
            field=models.DateField(verbose_name='First Race Date'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_time',
            field=models.DateField(verbose_name='Last Race Date'),
        ),
    ]
