# Generated by Django 4.0.4 on 2022-05-14 07:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0003_player_athlete_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='player',
        ),
        migrations.AddField(
            model_name='athlete',
            name='player',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
