# Generated by Django 4.0.4 on 2022-05-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0006_alter_race_time_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='special_class',
            field=models.CharField(default='oggetto', max_length=50),
        ),
    ]
