# Generated by Django 4.0.4 on 2022-05-21 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0007_special_special_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athlete',
            old_name='player',
            new_name='players',
        ),
    ]
