# Generated by Django 4.0.4 on 2022-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0008_rename_player_athlete_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='franchs',
            field=models.IntegerField(blank=True, default=200),
        ),
    ]
