# Generated by Django 4.0.4 on 2022-05-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0009_player_franchs'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='Prova', max_length=200),
        ),
    ]
