# Generated by Django 4.0.4 on 2022-05-28 05:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0010_player_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='born',
            field=models.DateField(default=datetime.date(2000, 1, 1), verbose_name='Date of Birth'),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.CharField(default='8+', max_length=200),
        ),
    ]
