# Generated by Django 4.1.2 on 2023-02-27 08:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0012_athlete_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player',
            name='franchs',
            field=models.IntegerField(blank=True, default=250),
        ),
        migrations.AlterField(
            model_name='special',
            name='special_class',
            field=models.CharField(choices=[('CCH', 'allenatore'), ('OBJ', 'oggetto'), ('STFF', 'staff')], default='oggetto', max_length=50),
        ),
    ]
