# Generated by Django 4.1.2 on 2023-03-06 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0014_athlete_is_user_athlete_price_alter_player_franchs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='is_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
