# Generated by Django 4.1.2 on 2023-03-06 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0015_alter_athlete_is_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='is_user',
        ),
        migrations.RemoveField(
            model_name='player',
            name='score',
        ),
        migrations.AddField(
            model_name='player',
            name='is_athlete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='fantapoma.athlete'),
        ),
    ]
