# Generated by Django 4.1.2 on 2023-03-06 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0016_remove_athlete_is_user_remove_player_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='is_athlete',
        ),
        migrations.AddField(
            model_name='athlete',
            name='is_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_athlete', to=settings.AUTH_USER_MODEL),
        ),
    ]
