# Generated by Django 4.1.2 on 2023-03-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0017_remove_player_is_athlete_athlete_is_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='nome'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='cognome'),
        ),
    ]
