# Generated by Django 4.1.2 on 2023-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0018_player_first_name_player_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='actions_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='athlete',
            name='race_points',
            field=models.IntegerField(default=0),
        ),
    ]
