# Generated by Django 4.1.2 on 2023-03-08 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0019_athlete_actions_points_athlete_race_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='points',
        ),
    ]
