# Generated by Django 4.1.2 on 2023-03-17 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0020_remove_athlete_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PALERMO SC', 'PALERMO SC'), ('TELIMAR', 'TELIMAR'), ('CUS PALERMO', 'CUS PALERMO'), ('PELOROROW', 'PELOROROW'), ('LAURIA CCR', 'LAURIA CCR'), ('AUGUSTA', 'AUGUSTA'), ('ORTIGIA', 'ORTIGIA'), ('UNIONE SICILIANA', 'UNIONE SICILIANA'), ('PARADISO', 'PARADISO')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='club',
        ),
        migrations.RemoveField(
            model_name='race',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='race',
            name='boat',
        ),
        migrations.RemoveField(
            model_name='race',
            name='cat',
        ),
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
        migrations.RemoveField(
            model_name='race',
            name='location',
        ),
        migrations.RemoveField(
            model_name='race',
            name='result',
        ),
        migrations.RemoveField(
            model_name='race',
            name='soc',
        ),
        migrations.AddField(
            model_name='race',
            name='boat_type',
            field=models.CharField(default='SINGOLO', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='category',
            field=models.CharField(default='SENIOR', max_length=20),
        ),
        migrations.AddField(
            model_name='race',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mix')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='race',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.CharField(choices=[('HEAT', 'Qualificazione'), ('FINAL', 'Finale')], default='FINAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bow_number', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8)])),
                ('athletes', models.ManyToManyField(to='fantapoma.athlete')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantapoma.club')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantapoma.race')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='athletes',
            field=models.ManyToManyField(to='fantapoma.athlete'),
        ),
        migrations.AlterField(
            model_name='race',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantapoma.event'),
        ),
    ]
