# Generated by Django 4.1.2 on 2023-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0021_club_event_remove_athlete_club_remove_race_athlete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
