# Generated by Django 4.1.2 on 2023-03-21 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0022_alter_race_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crew',
            name='athletes',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='club',
        ),
        migrations.RemoveField(
            model_name='crew',
            name='race',
        ),
        migrations.RemoveField(
            model_name='race',
            name='event',
        ),
        migrations.DeleteModel(
            name='Club',
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
