# Generated by Django 4.1.2 on 2023-04-17 05:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0023_remove_crew_athletes_remove_crew_club_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Athlete',
            new_name='FantaAthlete',
        ),
    ]
