# Generated by Django 4.1.2 on 2024-01-26 05:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0024_rename_athlete_fantaathlete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantaathlete',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='athlete_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
