# Generated by Django 4.1.2 on 2024-01-26 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0016_crew_result'),
        ('fantapoma', '0025_alter_fantaathlete_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantaathlete',
            name='athlete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.athlete'),
        ),
        migrations.AlterField(
            model_name='fantaathlete',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='athletes_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
