# Generated by Django 4.1.2 on 2024-02-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0026_fantaathlete_athlete_alter_fantaathlete_players'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantaathlete',
            name='first',
        ),
        migrations.RemoveField(
            model_name='fantaathlete',
            name='second',
        ),
        migrations.RemoveField(
            model_name='fantaathlete',
            name='third',
        ),
        migrations.RemoveField(
            model_name='fantaathlete',
            name='total',
        ),
    ]
