# Generated by Django 4.1.2 on 2024-02-27 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0027_remove_fantaathlete_first_remove_fantaathlete_second_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantaathlete',
            name='release_date',
            field=models.DateField(default=datetime.date(2024, 1, 1), verbose_name='Release Date'),
        ),
    ]
