# Generated by Django 4.1.2 on 2024-04-08 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0028_fantaathlete_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='cox',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cox', to='fantapoma.fantaathlete'),
        ),
    ]
