# Generated by Django 4.1.2 on 2024-04-12 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fantapoma', '0029_player_cox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special',
            name='player',
        ),
        migrations.AddField(
            model_name='special',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='specials_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
