# Generated by Django 4.1.2 on 2024-04-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0030_remove_special_player_special_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='special',
            old_name='points',
            new_name='price',
        ),
    ]
