# Generated by Django 4.1.2 on 2024-04-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantapoma', '0031_rename_points_special_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='franchs',
            field=models.IntegerField(blank=True, default=400),
        ),
    ]
