# Generated by Django 4.1.2 on 2024-04-15 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_race_enrolled'),
        ('fantapoma', '0033_fantaathleteeventscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantaathleteeventscore',
            name='has_hat',
            field=models.BooleanField(default=False, verbose_name='Indossare un cappellino'),
        ),
        migrations.AddField(
            model_name='fantaathleteeventscore',
            name='has_red_tshirt',
            field=models.BooleanField(default=False, verbose_name='Indossare una maglietta rossa'),
        ),
        migrations.AddField(
            model_name='fantaathleteeventscore',
            name='has_sunglasses',
            field=models.BooleanField(default=False, verbose_name='Indossare occhiali da sole'),
        ),
        migrations.AddField(
            model_name='fantaathleteeventscore',
            name='has_supporter',
            field=models.BooleanField(default=False, verbose_name='Portare un #scpsupporter'),
        ),
        migrations.CreateModel(
            name='PlayerEventScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantapoma.player')),
            ],
        ),
    ]
